"""
simulation.py
-------------
State preparation, QSP measurement sequences, and high-level simulation
drivers for the qubit–cavity cQED system.

All simulations assume the Hilbert space:   qubit ⊗ Fock(max_ph)

Qubit basis:  |0⟩ = |g⟩ (success),  |1⟩ = |e⟩ (failure)
"""

import numpy as np
from qutip import (
    basis, tensor, qeye, destroy, coherent,
    sigmax, sigmaz, expect,
    mesolve, sesolve,
)

from .pulses import (
    Phase_to_time, Phase_to_time_Wz,
    H_full_reduced, H_full_reduced_Wz,
    C_OPS,
)
from .number_theory import rk_find_best_prime


# ---------------------------------------------------------------------------
# State preparation
# ---------------------------------------------------------------------------

def prep_Coh_State(g_c, c_ops, max_ph, nbar):
    """
    Prepare an approximate coherent state |α⟩ (α = √nbar) in the cavity
    by driving a displacement Hamiltonian H = i g_c √nbar (a† - a) from
    the vacuum for time 1/g_c, with collapse operators c_ops.

    Parameters
    ----------
    g_c : float
        Displacement drive strength.
    c_ops : list of Qobj
        Collapse operators (can be empty for unitary displacement).
    max_ph : int
        Cavity Hilbert-space dimension.
    nbar : float
        Target mean photon number (|α|² = nbar).

    Returns
    -------
    Qobj
        Density matrix of the prepared state.
    """
    a = destroy(max_ph)
    psi_0 = tensor(
        basis(2, 0) * basis(2, 0).dag(),
        basis(max_ph, 0) * basis(max_ph, 0).dag(),
    )
    time_prep = np.linspace(0, 1 / g_c, 1000)
    result = mesolve(
        1j * g_c * np.sqrt(np.abs(nbar)) * tensor(qeye(2), a - a.dag()),
        psi_0,
        time_prep,
        c_ops,
    )
    return result.states[-1]


# ---------------------------------------------------------------------------
# Single QSP measurement
# ---------------------------------------------------------------------------

def qsp_meas(psi_0, time_list, H_full, c_ops, args):
    """
    Evolve psi_0 through one complete QSP pulse sequence.

    The time list is traversed segment by segment. Each segment uses either
    mesolve (open system, args='Diss') or sesolve (closed system).

    Parameters
    ----------
    psi_0 : Qobj
        Initial state (ket or density matrix).
    time_list : ndarray
        Ordered time markers generated by Phase_to_time[_Wz].
    H_full : list
        QuTiP time-dependent Hamiltonian.
    c_ops : list of Qobj
        Collapse operators (ignored for 'NoDiss').
    args : str
        'Diss'   – open-system simulation via mesolve.
        anything else – closed-system via sesolve.

    Returns
    -------
    Qobj
        State after the full pulse sequence.
    """
    for j in np.arange(len(time_list) - 1):
        t_start = time_list[j]
        t_stop = time_list[j + 1]
        if t_start == t_stop:
            continue
        t_span = np.linspace(t_start, t_stop, 100)
        solver_args = {'time_list': time_list}
        if args == 'Diss':
            result = mesolve(H_full, psi_0, t_span, c_ops, [], args=solver_args)
        else:
            result = sesolve(H_full, psi_0, t_span, args=solver_args)
        psi_0 = result.states[-1]
    return psi_0


# ---------------------------------------------------------------------------
# Repeated QSP measurements
# ---------------------------------------------------------------------------

def multiple_meas(psi_0, time_list, outcome_list, H_full, c_ops, args):
    """
    Apply len(outcome_list) sequential QSP measurements to psi_0,
    projecting onto the specified qubit outcome after each one.

    Parameters
    ----------
    psi_0 : Qobj
        Initial state.
    time_list : ndarray
        Pulse time markers.
    outcome_list : array-like of int
        Desired qubit measurement outcomes (0 = success, 1 = failure).
    H_full : list
        Time-dependent Hamiltonian.
    c_ops : list of Qobj
        Collapse operators.
    args : str
        'Diss' or anything else (see qsp_meas).

    Returns
    -------
    psi_out_list : list of Qobj
        Post-measurement states after each round.
    cumul_prob : ndarray
        Cumulative probability of the observed outcome sequence.
    """
    max_ph = psi_0.dims[0][1]
    succ = tensor(basis(2, 0) * basis(2, 0).dag(), qeye(max_ph))
    fail = tensor(basis(2, 1) * basis(2, 1).dag(), qeye(max_ph))

    cumul_prob = [1]
    psi_out_list = []

    for j in np.arange(len(outcome_list)):
        output_state = qsp_meas(psi_0, time_list, H_full, c_ops, args)
        print(f'  measurement {int(j)} complete')

        if outcome_list[j] == 0:
            prob = expect(succ, output_state)
            if args == 'Diss':
                post = succ * output_state * succ
            else:
                post = succ * output_state
        else:
            prob = expect(fail, output_state)
            if args == 'Diss':
                post = fail * output_state * fail
            else:
                post = fail * output_state

        post = post / post.norm()
        cumul_prob = np.append(cumul_prob, cumul_prob[-1] * prob)
        psi_out_list.append(post)
        psi_0 = post

    return psi_out_list, cumul_prob


# ---------------------------------------------------------------------------
# High-level simulation drivers
# ---------------------------------------------------------------------------

def _build_initial_state(statetype, nbar_var, max_ph_var, custom_list):
    """Internal: construct the initial qubit–cavity state."""
    if statetype == 'Fock':
        return tensor(basis(2, 0), basis(max_ph_var, nbar_var))
    elif statetype == 'FockFromCoh':
        return tensor(
            basis(2, 0),
            coherent(max_ph_var, np.sqrt(nbar_var), offset=0, method='operator'),
        )
    elif statetype == 'Cat':
        return tensor(
            basis(2, 0),
            coherent(max_ph_var, np.sqrt(nbar_var), offset=0, method='operator'),
        )
    elif statetype == 'CustomFock':
        psi = 0 * tensor(basis(2, 0), basis(max_ph_var, 0))
        for shift in custom_list:
            psi = psi + tensor(basis(2, 0), basis(max_ph_var, nbar_var + shift))
        return psi / psi.norm()
    elif statetype == 'Fock_2_meas':
        return tensor(
            basis(2, 0),
            coherent(max_ph_var, np.sqrt(nbar_var), offset=0, method='operator'),
        )
    else:
        raise ValueError(f"Unknown statetype: '{statetype}'")


def _build_c_ops(diss_type, gamma_c, gamma_qr, gamma_qz, n_crit, max_ph_var):
    """Internal: construct collapse operators for the requested noise model."""
    if diss_type == 'CavOnly':
        return C_OPS(gamma_c, 0, 0, 0, n_crit, max_ph_var)
    elif diss_type == 'NoQDeph':
        return C_OPS(gamma_c, 0, gamma_qr, 0, n_crit, max_ph_var)
    elif diss_type == 'QDecOnly':
        return C_OPS(0, 0, gamma_qr, 0, n_crit, max_ph_var)
    elif diss_type == 'QDephOnly':
        return C_OPS(0, 0, 0, gamma_qz, n_crit, max_ph_var)
    elif diss_type == 'Full':
        return C_OPS(gamma_c, 0, gamma_qr, gamma_qz, n_crit, max_ph_var)
    else:
        raise ValueError(f"Unknown diss_type: '{diss_type}'")


def nice_sim_multiple(conv, num_list, output_list, cancel, arg_list,
                      custom_list, param_lib):
    """
    Sweep over photon numbers and run QSP measurement sequences.

    Parameters
    ----------
    conv : str
        'Wx' – use σ_x signal basis (Phase_to_time + H_full_reduced).
        'Wz' – use σ_z signal basis (Phase_to_time_Wz + H_full_reduced_Wz).
    num_list : array-like of int
        Target photon numbers to sweep.
    output_list : array-like of int
        Qubit measurement outcomes (0/1) for each round.
    cancel : str
        Cancellation mode: 'cancel_SQ', 'full_cancel', or 'half_cancel'.
    arg_list : list
        [diss_arg, statetype, diss_type]
        • diss_arg  : 'Diss' or 'NoDiss'
        • statetype : 'Fock', 'FockFromCoh', 'Cat', 'CustomFock', 'Fock_2_meas'
        • diss_type : 'CavOnly', 'NoQDeph', 'QDecOnly', 'QDephOnly', 'Full'
    custom_list : array-like
        Fock-number offsets (only used for statetype='CustomFock').
    param_lib : dict
        Must contain: 'chi', 'omega_con', 'gamma_c', 'gamma_qr',
                      'gamma_qz', 'n_crit'.

    Returns
    -------
    state_list : list of Qobj
        Final state after all measurements, one per nbar in num_list.
    state_2_list : list of Qobj
        Second-round states (only populated for statetype='Fock_2_meas').
    succ_list : list
        Final cumulative success probability per nbar.
    """
    diss_arg, statetype, diss_type = arg_list
    chi = param_lib['chi']
    omega_con = param_lib['omega_con']
    gamma_c = param_lib['gamma_c']
    gamma_qr = param_lib['gamma_qr']
    gamma_qz = param_lib['gamma_qz']
    n_crit = param_lib['n_crit']

    state_list = []
    state_2_list = []
    succ_list = []
    output_list = np.array(output_list)

    for nbar_var in num_list:
        max_ph_var = nbar_var + 100
        psi_0 = _build_initial_state(statetype, nbar_var, max_ph_var, custom_list)
        c_ops_var = _build_c_ops(diss_type, gamma_c, gamma_qr, gamma_qz,
                                  n_crit, max_ph_var)

        # Determine r and k lists
        if statetype == 'Fock_2_meas':
            params = rk_find_best_prime(nbar_var, 4)
            r_list = np.flip(params[1])
            k_list = np.flip(params[2])
        elif statetype == 'Cat':
            r_list = [np.ceil(np.sqrt(nbar_var))]
            k_list = [0]
        else:
            r_list = [nbar_var]
            k_list = [0]

        output_list_var = output_list.copy()
        psi_0_list = []

        for j in np.arange(len(r_list)):
            # For Fock_2_meas, flip outcomes on the second measurement round
            if len(output_list) % 2 == 1 and j == 1:
                output_list_var = (output_list_var + 1) % 2

            r_var = int(r_list[j])
            k_var = int(k_list[j])

            if conv == 'Wx':
                time_list = Phase_to_time(chi, omega_con, r_var, r_var, k_var)
                H_full = H_full_reduced(chi, omega_con, max_ph_var,
                                        nbar_var, cancel, 'Dispersive')
            elif conv == 'Wz':
                time_list = Phase_to_time_Wz(chi, omega_con, r_var, r_var, k_var)
                H_full = H_full_reduced_Wz(chi, omega_con, max_ph_var,
                                            nbar_var, cancel, 'Dispersive')
            else:
                raise ValueError(f"Unknown conv basis: '{conv}'")

            psi_r_test = multiple_meas(
                psi_0, time_list, output_list_var, H_full, c_ops_var, 'Diss'
            )
            psi_0 = psi_r_test[0][-1]
            psi_0_list.append(psi_0)

        state_list.append(psi_0_list[0])
        if statetype == 'Fock_2_meas':
            state_2_list.append(psi_0_list[1])
        succ_list.append(psi_r_test[1][-1])

    return state_list, state_2_list, succ_list


def nice_sim_multiple_rdep(nbar, r_list, output_list, cancel, args, param_lib):
    """
    Sweep over QSP polynomial degrees r for a fixed photon number nbar,
    using the Wz-basis.

    Parameters
    ----------
    nbar : int
        Fixed target photon number.
    r_list : array-like of int
        QSP degrees to sweep.
    output_list : array-like of int
        Measurement outcomes.
    cancel : str
        Cancellation mode.
    args : str
        'Diss' or 'NoDiss'.
    param_lib : dict
        System parameters (see nice_sim_multiple).

    Returns
    -------
    state_list : list of Qobj
    succ_list  : list of ndarray (cumulative probabilities per r)
    """
    chi = param_lib['chi']
    omega_con = param_lib['omega_con']
    gamma_c = param_lib['gamma_c']
    gamma_qr = param_lib['gamma_qr']
    gamma_qz = param_lib['gamma_qz']
    n_crit = param_lib['n_crit']

    max_ph_var = nbar + 100
    k_var = 0
    psi_0 = tensor(
        basis(2, 0),
        coherent(max_ph_var, np.sqrt(nbar), offset=0, method='operator'),
    )
    c_ops_var = C_OPS(gamma_c, 0, gamma_qr, gamma_qz, n_crit, max_ph_var)

    state_list = []
    succ_list = []

    for r_var in r_list:
        print(f'r = {r_var}')
        time_list = Phase_to_time_Wz(chi, omega_con, r_var, r_var, k_var)
        H_full = H_full_reduced_Wz(chi, omega_con, max_ph_var, nbar, cancel,
                                    'Dispersive')
        result = multiple_meas(psi_0, time_list, output_list, H_full,
                                c_ops_var, args)
        state_list.append(result[0][-1])
        succ_list.append(result[1])

    return state_list, succ_list


# ---------------------------------------------------------------------------
# Fock-state preparation wrappers
# ---------------------------------------------------------------------------

def Fock_prep(chi, omega_con, c_ops, psi_init, nbar, repeat, cancel, args):
    """
    Prepare a Fock state |nbar⟩ using the two-step CRT measurement protocol.

    Uses rk_find_best_prime to find coprime (r1, r2) and applies measurements
    sequentially to narrow the photon-number distribution.

    Parameters
    ----------
    chi, omega_con : float
        System parameters.
    c_ops : list of Qobj
        Collapse operators.
    psi_init : Qobj
        Initial state (e.g. coherent state in the cavity).
    nbar : int
        Target Fock number.
    repeat : int
        Number of QSP rounds per r value.
    cancel : str
        Cancellation mode.
    args : str
        'Diss' or 'NoDiss'.

    Returns
    -------
    psi_0_list : list of Qobj
    prob_list  : ndarray   (cumulative success probabilities)
    trace_dist : float
    fid        : float     (occupation probability of Fock state |nbar⟩)
    """
    from .measurement import number_dist
    max_ph = psi_init.dims[0][1]
    H_full = H_full_reduced(chi, omega_con, max_ph, nbar, cancel, 'Dispersive')

    psi_0 = psi_init
    psi_0_list = [psi_0]
    prob_list = [1]

    params = rk_find_best_prime(nbar, 3)
    r_list = np.flip(params[1])
    k_list = np.flip(params[2])

    for j in np.arange(len(r_list)):
        r = int(r_list[j])
        k = int(k_list[j])
        time_list = Phase_to_time(chi, omega_con, r, r, k)
        outcome_list = np.zeros(repeat)
        interm_state = multiple_meas(psi_0, time_list, outcome_list,
                                      H_full, c_ops, args)
        psi_0 = interm_state[0][-1]
        psi_0_list.append(psi_0)
        prob_list = np.append(prob_list, prob_list[-1] * interm_state[1][-1])

    from qutip import tracedist
    fid = number_dist(interm_state[0][-1], max_ph)[nbar]
    psi_target = tensor(basis(2, 0), basis(max_ph, nbar))
    psi_target = psi_target * psi_target.dag()
    trace_dist = tracedist(interm_state[0][-1], psi_target)
    return psi_0_list, prob_list, trace_dist, fid
